version: '3.8'

services:
  app:
    build:
      context: .
      dns:
        - 8.8.8.8
    container_name: mcp-server-google-analytics
    dns:
      - 8.8.8.8
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    env_file:
      - .env